// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAecCmDFcddi9ZSzSyu6c_qBA5HjlVkHZU',
    appId: '1:637880034677:android:ea0d3b93632905bf6adf3c',
    messagingSenderId: '637880034677',
    projectId: 'uni-syllubi',
    storageBucket: 'uni-syllubi.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXrpZONl3xljHUIfOzMebrTXzp1kc4-5U',
    appId: '1:637880034677:ios:bb42cfc4065066c16adf3c',
    messagingSenderId: '637880034677',
    projectId: 'uni-syllubi',
    storageBucket: 'uni-syllubi.firebasestorage.app',
    androidClientId: '637880034677-4lb4sslfjqildkl5pea536raj04f0ouq.apps.googleusercontent.com',
    iosClientId: '637880034677-s8342iig8209t7v9t3n5tjqs9q9m0tau.apps.googleusercontent.com',
    iosBundleId: 'com.faisalalnasri.aaTemplate',
  );
}
