// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDFxigo1Wt0v3aps9WkyL6VqFK3DVMK4E',
    appId: '1:594792346236:android:e416dae6bebeb354d1cff9',
    messagingSenderId: '594792346236',
    projectId: 'aatemplate-24a4d',
    storageBucket: 'aatemplate-24a4d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC53qN-EZPdN5v51SOre7hiNcSid89CvaQ',
    appId: '1:594792346236:ios:da7a5951e8ee2dc3d1cff9',
    messagingSenderId: '594792346236',
    projectId: 'aatemplate-24a4d',
    storageBucket: 'aatemplate-24a4d.firebasestorage.app',
    androidClientId: '594792346236-oj1spsr3kj0qh3f67v6mft4k8ad1dbam.apps.googleusercontent.com',
    iosClientId: '594792346236-ousa2lauhre5mbp7togk4c98hq5iaut0.apps.googleusercontent.com',
    iosBundleId: 'com.faisalalnasri.aaTemplate',
  );
}
